import { StyleSheet, Platform } from "react-native";

const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#082754",
    height: "100%",
  },
  menuContainer: {
    flex: 1,
    backgroundColor: "#082754",
  },
  txth1: {
    color: "#ffffff",
    fontSize: 24,
    textAlign: "center",
    fontWeight: "700",
    // lineHeight: 31,
    letterSpacing: -0.17,
  },
  txth2: {
    color: "#ffffff",
    fontSize: 19,
    textAlign: "center",
    fontWeight: "500",
    // lineHeight: 27,
    letterSpacing: -0.17,
  },
  txth3: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: -0.17,
  },
  static_white_background: {
    backgroundColor: "#ECEDF6",
    position: "absolute",
    bottom: Platform.OS === "ios" ? -34 : 0,
    left: 0,
    right: 0,
    height: "77%",

    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  cellroot: {
    width: 40,
    height: 40,
    lineHeight: 38,
    fontSize: 22,
    borderColor: "#658FCB",
    borderBottomWidth: 2,
    textAlign: "center",
    color: "#ffffff",
    marginLeft: 10,
  },
  cell: {
    lineHeight: 38,
    fontSize: 22,
    color: "#ffffff",
    textAlign: "center",
  },
  focusCellroot: {
    borderColor: "#ffffff",
  },
  btn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    backgroundColor: "#84C441",
    width: "100%",
    height: 48,
    flexDirection: "row",
  },
  btn40: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    paddingHorizontal: 25,
    borderRadius: 8,
    backgroundColor: "#84C441",
    width: "100%",
    height: 40,
    flexDirection: "row",
  },
  btnText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 16,
  },
  txtQuestian: {
    textAlign: "center",
    color: "#A0C1EF",
    lineHeight: 31,
    letterSpacing: -0.17,
    fontSize: 13,
    marginTop: 15,
    marginBottom: -15,
  },
  btnBorder: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    marginTop: "5%",
    borderColor: "#84C441",
    width: "100%",
    borderWidth: 2,
    height: 48,
  },
  btntxtSearch: {
    color: "#84C441",
    fontWeight: "700",
  },
  txtInput: {
    color: "#ffffff",
    fontSize: 16,
    borderBottomColor: "#658FCB",
    borderBottomWidth: 2,
    paddingRight: 40,
    height: 30,
  },
  icon: {
    position: "absolute",
    right: 10,
    color: "#CCD1D8",
    fontSize: 20,
  },
  searchResultsContainer: {
    width: "100%",
    backgroundColor: "#f5f5f5",
    borderColor: "#e1e1e1",
    borderWidth: 1,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    zIndex: 999,
  },
  loading: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,    
    alignItems: "center",
    justifyContent: "center",    
  },
  CheckBox: {
    // transform: [{ scaleX: 1 }, { scaleY: 1 }],    
    margin:8
  },
  remembermeSwitch: {
    transform: [{ scaleX: 0.6 }, { scaleY: 0.6 }],
  },
  txtCheck: {
    color: "#ffffff",
    textAlign: "center",
    lineHeight: 31,
    letterSpacing: -0.17,
    fontWeight: "500",
  },
  btnBiokit: {
    color: "white",
    lineHeight: 31,
    letterSpacing: -0.17,
    fontWeight: "500",
  },
  btnChangedist: {
    fontWeight: "bold",
    fontSize: 18,
    borderBottomWidth: 2,
  },
  backgroudMenu: {
    backgroundColor: "#ECEDF6",
    height: "100%",
    borderRadius: 40,
    marginTop: "33%",
  },
  announcementImg: {
    width: 130,
    height: 130,
    borderRadius: 8,
    marginTop: 10,
  },
  profileImg: {
    width: 70,
    height: 70,
    borderRadius: 8,
  },
  pickerStyle: {
    height: 150,
    width: "80%",
    color: "#344953",
    justifyContent: "center",
  },
  animatedView: {
    width: 15,
    height: 8,
    backgroundColor: "#619B26",
    position: "absolute",
    bottom: Platform.OS === "ios" ? 62 : 62,
    left: "11%",
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    zIndex: 999,
  },
  parentName: {
    fontSize: 13,
    fontWeight: "bold",
    //opacity: 0.8,
    color: "#002952",
    marginBottom: 5,
  },
  homephone: {
    fontSize: 15,
    marginBottom: 5,
  },
});

export default commonStyles;
