import { Platform, StyleSheet } from "react-native";

const themes = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#082754',
    height: '100%',
  },
  containerPadding: {
    paddingBottom: '5%',
    paddingLeft: '5%',
    paddingRight: '5%',
    paddingTop: '2%',
  },
  menuContainer: {
    flex: 1,
    backgroundColor: '#082754',
  },

  imgBackground: {
    justifyContent: "center",
    resizeMode: "cover",
    flex: 1,
  },
  txtview: {
    marginTop: '10%',
  },
  txtviewIOS: {
    marginTop: '10%',
    zIndex: 1,
  },
  txth1: {
    color: '#ffffff',
    fontSize: 24,
    textAlign: "center",
    fontWeight: '700',
    lineHeight: 31,
    letterSpacing: -0.17,
  },
  txth2: {
    color: '#ffffff',
    fontSize: 19,
    textAlign: "center",
    fontWeight: '500',
    lineHeight: 27,
    letterSpacing: -0.17,
  },
  txth3: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: "center",
    fontWeight: '500',
    lineHeight: 27,
    letterSpacing: -0.17,
  },
  txtMenuh1: {
    color: '#ffffff',
    fontSize: 19,
    textAlign: "center",
    fontWeight: '500',
    lineHeight: 27,
    letterSpacing: -0.17,
  },
  txtQuestian: {
    textAlign: "center",
    color: "#A0C1EF",
    lineHeight: 31,
    letterSpacing: -0.17,
    fontSize: 13,
    marginTop: 15,
    marginBottom: -15,
  },
  txtInput: {
    color: '#ffffff',
    fontSize: 16,
    borderBottomColor: "#658FCB",
    borderBottomWidth: 2,
    paddingRight: 25,
  },
  cellroot: {
    width: 40,
    height: 40,
    lineHeight: 38,
    fontSize: 22,
    borderColor: "#658FCB",
    borderBottomWidth: 2,
    textAlign: "center",
    color: '#ffffff',
    marginLeft: 10,
  },
  cell: {
    lineHeight: 38,
    fontSize: 22,
    color: '#ffffff',
    textAlign: "center",
  },
  focusCellroot: {
    borderColor: '#ffffff',
  },
  field: {
    marginTop: '5%',
    height: 40,
  },
  fieldPass: {
    marginBottom: 5,
    marginTop: 10,
    height: 40,
  },
  txtCheck: {
    color: '#ffffff',
    textAlign: "center",
    lineHeight: 31,
    letterSpacing: -0.17,
    fontWeight: '500',
  },
  checkboxContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    left: -5,
  },
  CheckBox: {
    margin:8
    // transform: [{ scaleX: 1 }, { scaleY: 1 }],
  },
  btn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    marginTop: '5%',
    backgroundColor: '#84C441',
    width: '100%',
    height: 48,
    flexDirection: "row",
  },
  btnBorder: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    marginTop: '5%',
    borderColor: "#84C441",
    width: '100%',
    borderWidth: 2,
    height: 48,
  },
  btnChangedist: {
    fontWeight: "bold",
    fontSize: 18,

    borderBottomWidth: 2,
  },
  idFieldStyle: {
    flexDirection: "row",
  },
  distStyle: {
    marginTop: '30%',
    alignItems: "center",
    justifyContent: "center",
  },
  btnText: {
    color: '#ffffff',
    fontWeight: '700',
  },

  btnBiokit: {
    color: "white",
    lineHeight: 31,
    letterSpacing: -0.17,
    fontWeight: '500',
  },
  txtDistError: {
    color: "red",
    textAlign: "center",
    fontWeight: '700',
    padding: 5,
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  btntxtSearch: {
    color: "#84C441",
    fontWeight: '700',
  },
  txtPartitioned: {},
  btnPadding: {
    width: '100%',
  },
  viewBox: {
    marginTop: '5%',
  },
  loginViewBox: {
    marginTop: '5%',
  },
  codeField: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    justifyContent: "center",
    marginLeft: -10,
  },
  icon: {
    position: "absolute",
    right: 2,
    color: "#CCD1D8",
    fontSize: 16,
  },
  moreIcons: {
    color: '#59687D',
    fontSize: 22,
  },
  backIcon: {
    fontSize: 24,
    color: '#ffffff',
  },
  backgroudMenu: {
    backgroundColor: '#ECEDF6',
    height: '100%',
    borderRadius: 40,
    marginTop: 130,
  },
  tabIcon: {
    justifyContent: "center",
  },
  tabnavStyle: {
    height: '20%',
  },
  backButton: {
    position: "absolute",
    left: 0,
    flex: 1,
    zIndex: 999,
    width: 20,
    height: 30,
  },
  backbtn: {
    position: "absolute",
    left: 25,
    flex: 1,
    zIndex: 999,
  },
  downloadButton: {
    position: "absolute",
    justifyContent: "flex-end",
    right: 25,
    flexDirection: "row",
    flex: 1,
    zIndex: 999,
  },
  idSavedBtn: {
    position: "absolute",
    justifyContent: "flex-end",
    right: 0,
    flexDirection: "row",
    flex: 1,
    zIndex: 999,
  },
  IdZview: {
    zIndex: 1,
    width: '100%',
  },

  idCard: {
    backgroundColor: '#ffffff',
    position: "absolute",
    width: '86%',
    height: "auto",
    minHeight: 500,
    left: '7%',
    borderRadius: 10,
    top: Platform.OS === "ios" ? "20%" : "15%",
    padding: '5%',
    flex: 1,
    zIndex: 999,
  },
  listViewTab: {
    position: "absolute",
    width: '100%',
    height: '85%',
    top: Platform.OS === "ios" ? "20%" : "15%",
    zIndex: 999,
  },
  moreTab: {
    backgroundColor: '#ffffff',
    position: "absolute",
    width: '86%',
    height: 490,
    left: '7%',
    borderRadius: 10,
    marginTop: '-25%',
    padding: '5%',
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalViewThreshold: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: '5%',
    alignItems: "center",
    shadowColor: "#6b6b6b",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 1,
    shadowOpacity: 0.7,
    shadowRadius: 60,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 15,
    paddingBottom: 15,
    width: '86%',
    height: 110,
  },
  modalView: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: '5%',
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 15,
    width: '86%',
    height: "auto",
  },
  viewMore: {
    padding: 15,
    flexDirection: "column",
    //marginTop:30
    zIndex: 999,
    position: "relative",
  },
  txtMore: {
    fontSize: 16,
    fontWeight: '500',
    height: 28,
    marginLeft: 15,
  },
  txtThreshold: {
    fontSize: 14,
    marginLeft: 15,
    marginBottom: 7,
  },
  txtinputThreshold: {
    borderBottomWidth: 1,
    borderBottomColor: "#6b6868",
    flexDirection: "row",
    width: '100%',
    height: 40,
  },
  btnView: {
    flexDirection: "row",
    right: '10%',
    position: "absolute",
    marginTop: 70,
  },
  thresholbBtnStyle: {
    fontWeight: '700',
    fontSize: 16,
  },
  fieldMore: {
    borderBottomColor: '#F0EDED',
    borderBottomWidth: 1,
    flexDirection: "row",
    marginTop: '10%',
  },
  image: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: '5%',
  },

  notificationSettings: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    width: '86%',
    marginBottom: 10,
    left: '7%',
    alignContent: "center",
    padding: 15,
  },
  notificationMOdel: {
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    flex: 1,
  },
  hNotification: {
    fontWeight: "bold",
    color: 'black',
    paddingTop: 5,
    paddingLeft: 15,
    fontSize: 16,
  },
  fieldNotification: {
    borderBottomColor: '#F0EDED',
    borderBottomWidth: 1,
    flexDirection: "row",
    marginTop: '5%',
  },
  toggleSwitch: {
    position: "absolute",
    right: 0,
    transform:
      Platform.OS === "ios"
        ? [{ scaleX: 0.6 }, { scaleY: 0.6 }]
        : [{ scaleX: 1 }, { scaleY: 1 }],
    bottom: 3,
  },
  remembermeSwitch: {
    transform: [{ scaleX: 0.6 }, { scaleY: 0.6 }],
  },
  profileImg: {
    height: 125,
    width: 125,
    borderRadius: 125 / 2,
  },
  idImgView: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: '3%',
  },
  idField: {
    borderBottomColor: '#F0EDED',
    borderBottomWidth: 2,
    marginTop: '1%',
  },
  idFieldSchool: {
    marginTop: '1%',
  },
  idRow: {
    flexDirection: "row",
    marginBottom: '5%',
  },
  idSubtxt1: {
    color: '#59687D',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  idSubtxt2: {
    color: '#59687D',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  idResult1: {
    color: '#656667',
    fontSize: 14,
    marginTop: 5,
    fontWeight: '500',
    flex: 1,
  },
  idResult2: {
    color: '#656667',
    fontSize: 14,
    flex: 1,
    marginTop: 5,
    fontWeight: '500',
  },
  idtxtName: {
    justifyContent: "center",
    textAlign: "center",
    fontWeight: '700',
    fontSize: 18,
    marginTop: 5,
    marginBottom: 5,
  },
  idtxt1: {
    justifyContent: "center",
    textAlign: "center",
    fontWeight: '700',
    fontSize: 18,
    color: "#84C441",
  },
  announcementViewtop: {
    backgroundColor: '#ffffff',
    width: '86%',
    height: 138,
    left: '7%',
    borderRadius: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 15,
    marginBottom: 6,
  },
  announcementView: {
    backgroundColor: '#ffffff',
    width: '86%',
    left: '5%',
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 5,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
  },
  flatlistSettingStyle: {
    flexGrow: 1,
    marginBottom: '0%',
  },
  boxScroll: {
    marginTop: '-23.15%',
  },
  headtxt: {
    fontWeight: '700',
    fontSize: 14,
    color: '#59687D',
  },
  announcementImg: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginTop: 10,
  },
  studName: {
    fontWeight: '700',
    fontSize: 14,
    marginLeft: 10,
    marginTop: 20,
  },
  studId: {
    fontWeight: '500',
    fontSize: 13,
    color: '#656667',
    marginLeft: 10,
    marginTop: 5,
  },
  studDetails: {
    borderTopColor: "#F0EDED",
    borderTopWidth: 2,
    flexDirection: "row",
    marginTop: 10,
  },
  barcode: {
    textAlign: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: '1%',
    //marginTop:'1%'
  },
  txtdetails: {
    color: 'black',
    fontWeight: '500',
    fontSize: 12,
    borderTopColor: "#F0EDED",
    borderTopWidth: 2,
    marginTop: 5,
    paddingTop: 5,
  },
  closeBtn: {
    position: "absolute",
    right: 10,
    top: 10,
    zIndex: 9,
    elevation: 5,
  },
  closeBtnImg: {
    width: 30,
    height: 30,
  },
  searchResultsContainer: {
    width: '100%',
    backgroundColor: '#f5f5f5',
    borderColor: "#e1e1e1",
    borderWidth: 1,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    zIndex: 999,
    padding: 5,
  },
  btntxtSerchDist: {
    marginBottom: 3,
  },
  loading: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  overlaycontainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#575757',
    opacity: 0.9,
  },
  animatedView: {
    width: 15,
    height: 8,
    backgroundColor: '#619B26',
    position: "absolute",
    bottom: Platform.OS === "ios" ? 62 : 62,
    left: '15%',
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    zIndex: 999,
  },
  animationPlaceholder: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    width: '86%',
    marginBottom: 10,
    left: '7%',
    alignContent: "center",
    padding: 15,
  },
});

export default themes;
